"""``import coordinax.main as cx``."""

__all__ = (  # distances
    "Distance",
    # angles
    "Angle",
    # charts
    "NoGlobalCartesianChartError",
    "CartesianProductChart",
    "cartesian_chart",
    "guess_chart",
    "cdict",
    "pt_map",
    "jac_pt_map",
    "cart1d",
    "radial1d",
    "time1d",
    "cart2d",
    "polar2d",
    "cart3d",
    "cyl3d",
    "sph3d",
    "lonlat_sph3d",
    "loncoslat_sph3d",
    "math_sph3d",
    "cartnd",
    # manifolds and atlases
    "EuclideanManifold",
    "Rn",
    "EuclideanMetric",
    "euclidean3d",
    "twosphere",
    "embedded_twosphere",
    "EmbeddedChart",
    "EmbeddedManifold",
    "CustomAtlas",
    "CustomManifold",
    # frames -- frames
    "noframe",
    # frame -- transforms
    "act",
    "frame_transition",
    "simplify",
    "Composed",
    "identity",
    "Rotate",
    "Translate",
    "Scale",
    "Shear",
    # representations
    "cconvert",
    "add",
    "subtract",
    "PointGeometry",
    "point_geom",
    "TangentGeometry",
    "tangent_geom",
    "NoBasis",
    "no_basis",
    "AbstractLinearBasis",
    "CoordinateBasis",
    "coord_basis",
    "PhysicalBasis",
    "phys_basis",
    "Location",
    "loc",
    "AbstractTangentSemanticKind",
    "Displacement",
    "dpl",
    "Velocity",
    "vel",
    "Acceleration",
    "acc",
    "Representation",
    "point",
    "coord_disp",
    "coord_vel",
    "coord_acc",
    "phys_disp",
    "phys_vel",
    "phys_acc",
    "tangent_map",
    "change_basis",
    # vectors
    "Point",
    "Coordinate",
    "Tangent",
    "ToUnitsOptions",
)

import contextlib

from coordinax.angles import Angle
from coordinax.charts import (
    CartesianProductChart,
    NoGlobalCartesianChartError,
    cart1d,
    cart2d,
    cart3d,
    cartesian_chart,
    cartnd,
    cdict,
    cyl3d,
    guess_chart,
    jac_pt_map,
    loncoslat_sph3d,
    lonlat_sph3d,
    math_sph3d,
    polar2d,
    pt_map,
    radial1d,
    sph3d,
    time1d,
)
from coordinax.distances import Distance
from coordinax.frames import frame_transition, noframe
from coordinax.manifolds import (
    CustomAtlas,
    CustomManifold,
    EmbeddedChart,
    EmbeddedManifold,
    EuclideanManifold,
    EuclideanMetric,
    Rn,
    embedded_twosphere,
    euclidean3d,
    twosphere,
)
from coordinax.representations import (
    AbstractLinearBasis,
    AbstractTangentSemanticKind,
    Acceleration,
    CoordinateBasis,
    Displacement,
    Location,
    NoBasis,
    PhysicalBasis,
    PointGeometry,
    Representation,
    TangentGeometry,
    Velocity,
    acc,
    add,
    cconvert,
    change_basis,
    coord_acc,
    coord_basis,
    coord_disp,
    coord_vel,
    dpl,
    loc,
    no_basis,
    phys_acc,
    phys_basis,
    phys_disp,
    phys_vel,
    point,
    point_geom,
    subtract,
    tangent_geom,
    tangent_map,
    vel,
)
from coordinax.transforms import (
    Composed,
    Rotate,
    Scale,
    Shear,
    Translate,
    act,
    identity,
    simplify,
)
from coordinax.vectors import Coordinate, Point, Tangent, ToUnitsOptions

# Import interop modules to register conversions and chart transitions.
with contextlib.suppress(ImportError):
    import coordinax.interop.astropy as _  # noqa: F401  # ty: ignore[unresolved-import,unused-ignore-comment]

# Clean up namespace
del contextlib
