"""`coordinax.r` Module."""

__all__ = (
    "cartesian_rep",
    "time_derivative_rep",
    "time_antiderivative_rep",
    # ===============================================
    "AbstractRepresentation",
    "AbstractPos",
    "AbstractVel",
    "AbstractAcc",
    # = 1D ======================================
    # - Cartesian ---------------------
    "CartPos1D",
    "cartpos1d",
    "CartVel1D",
    "cartvel1d",
    "CartAcc1D",
    "cartacc1d",
    # - Radial ---------------------
    "RadialPos",
    "radialpos",
    "RadialVel",
    "radialvel",
    "RadialAcc",
    "radialacc",
    # = 2D ======================================
    # - Cartesian ---------------------
    "CartPos2D",
    "cartpos2d",
    "CartVel2D",
    "cartvel2d",
    "CartAcc2D",
    "cartacc2d",
    # - Polar ---------------------
    "PolarPos",
    "polarpos",
    "PolarVel",
    "polarvel",
    "PolarAcc",
    "polaracc",
    # - TwoSphere ---------------------
    "TwoSpherePos",
    "twospherepos",
    "TwoSphereVel",
    "twospherevel",
    "TwoSphereAcc",
    "twosphereacc",
    # = 3D ======================================
    # - Cartesian ---------------------
    "CartPos3D",
    "cartpos3d",
    "CartVel3D",
    "cartvel3d",
    "CartAcc3D",
    "cartacc3d",
    # - Cylindrical ---------------------
    "CylindricalPos",
    "cylindricalpos",
    "CylindricalVel",
    "cylindricalvel",
    "CylindricalAcc",
    "cylindricalacc",
    # - Spherical ---------------------
    "AbstractSphericalPos",
    "AbstractSphericalVel",
    "AbstractSphericalAcc",
    "SphericalPos",
    "sphericalpos",
    "SphericalVel",
    "sphericalvel",
    "SphericalAcc",
    "sphericalacc",
    # - LonLatSpherical ---------------
    "LonLatSphericalPos",
    "lonlatsphericalpos",
    "LonLatSphericalVel",
    "lonlatsphericalvel",
    "LonLatSphericalAcc",
    "lonlatsphericalacc",
    # - LonCosLatSpherical ---------------
    "LonCosLatSphericalPos",
    "loncoslatsphericalpos",
    "LonCosLatSphericalVel",
    "loncoslatsphericalvel",
    "LonCosLatSphericalAcc",
    "loncoslatsphericalacc",
    # - MathSpherical -----------------
    "MathSphericalPos",
    "mathsphericalpos",
    "MathSphericalVel",
    "mathsphericalvel",
    "MathSphericalAcc",
    "mathsphericalacc",
    # - ProlateSpheroidal -------------
    "ProlateSpheroidalPos",
    "prolatespheroidalpos",
    "ProlateSpheroidalVel",
    "prolatespheroidalvel",
    "ProlateSpheroidalAcc",
    "prolatespheroidalacc",
    # = 4D ======================================
    # - SpaceTime ---------------------
    "CartSpaceTime",
    "cartspacetime",
    "SpaceTime",
    # There's no instance of SpaceTime to export
    # = 6D ======================================
    # - PoincarePolar -----------------
    "PoincarePolarRep",
    "poincarepolar",
    # = N-D =====================================
    # - CartesianND -------------------
    "CartPosND",
    "cartndpos",
    "CartVelND",
    "cartndvel",
    "CartAccND",
    "cartndacc",
)

from .setup_package import RUNTIME_TYPECHECKER, install_import_hook

with install_import_hook("coordinax.r"):
    from ._src.vectors.representations import (
        AbstractAcc,
        AbstractPos,
        AbstractRepresentation,
        AbstractSphericalAcc,
        AbstractSphericalPos,
        AbstractSphericalVel,
        AbstractVel,
        CartAcc1D,
        CartAcc2D,
        CartAcc3D,
        CartAccND,
        CartPos1D,
        CartPos2D,
        CartPos3D,
        CartPosND,
        CartSpaceTime,
        CartVel1D,
        CartVel2D,
        CartVel3D,
        CartVelND,
        CylindricalAcc,
        CylindricalPos,
        CylindricalVel,
        LonCosLatSphericalAcc,
        LonCosLatSphericalPos,
        LonCosLatSphericalVel,
        LonLatSphericalAcc,
        LonLatSphericalPos,
        LonLatSphericalVel,
        MathSphericalAcc,
        MathSphericalPos,
        MathSphericalVel,
        PoincarePolarRep,
        PolarAcc,
        PolarPos,
        PolarVel,
        ProlateSpheroidalAcc,
        ProlateSpheroidalPos,
        ProlateSpheroidalVel,
        RadialAcc,
        RadialPos,
        RadialVel,
        SpaceTime,
        SphericalAcc,
        SphericalPos,
        SphericalVel,
        TwoSphereAcc,
        TwoSpherePos,
        TwoSphereVel,
        cartacc1d,
        cartacc2d,
        cartacc3d,
        cartesian_rep,
        cartndacc,
        cartndpos,
        cartndvel,
        cartpos1d,
        cartpos2d,
        cartpos3d,
        cartspacetime,
        cartvel1d,
        cartvel2d,
        cartvel3d,
        cylindricalacc,
        cylindricalpos,
        cylindricalvel,
        loncoslatsphericalacc,
        loncoslatsphericalpos,
        loncoslatsphericalvel,
        lonlatsphericalacc,
        lonlatsphericalpos,
        lonlatsphericalvel,
        mathsphericalacc,
        mathsphericalpos,
        mathsphericalvel,
        poincarepolar,
        polaracc,
        polarpos,
        polarvel,
        prolatespheroidalacc,
        prolatespheroidalpos,
        prolatespheroidalvel,
        radialacc,
        radialpos,
        radialvel,
        sphericalacc,
        sphericalpos,
        sphericalvel,
        time_antiderivative_rep,
        time_derivative_rep,
        twosphereacc,
        twospherepos,
        twospherevel,
    )


del install_import_hook, RUNTIME_TYPECHECKER
