name: CD

on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Many color libraries just need this to be set to any value, but at least
  # one distinguishes color depth, where "3" -> "256-bit color".
  FORCE_COLOR: 3

jobs:
  build-package:
    name: Distribution build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: hynek/build-and-inspect-python-package@c52c3a4710070b50470d903818a7b25115dcd076 # v2.13.0

  # Upload to TestPyPI on every commit to main.
  test-publish:
    needs: [build-package]
    name: Publish to TestPyPI
    environment: testpypi
    runs-on: ubuntu-latest
    if: >
      (github.repository_owner == 'GalacticDynamics' && github.event_name ==
      'push' && github.ref == 'refs/heads/main') || (github.event_name ==
      'release' && github.event.action == 'published')

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: Packages
          path: dist

      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          attestations: true
          repository-url: https://test.pypi.org/legacy/

  # Upload to PyPI on every release.
  publish:
    needs: [test-publish]
    name: Publish to PyPI
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if:
      github.repository_owner == 'GalacticDynamics' && github.event.action ==
      'published'

    steps:
      - name: Download built package
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          attestations: true
